- name: "Configure firewall"
  hosts: localhost
  connection: local
  tasks:
    - name: "enable rsyslog"
      service:
        name: rsyslog
        enabled: yes
        state: started
      become: yes
      become_method: sudo

    - name: "Configure UFW"
      ufw:
        state: enabled
        policy: allow
        direction: incoming
        logging: full
      become: yes
      become_method: sudo
    
    - name: "log SYN packets in INPUT chain"
      lineinfile:
        path: /etc/ufw/after.rules
        line: '-A ufw-after-input -p tcp --syn -j LOG --log-prefix "[UFW-SYN-LOG]"'
        insertbefore: "# don't delete the 'COMMIT' line or these rules won't be processed"
      become: yes
      become_method: sudo
